# $NetBSD$

DISTNAME=	${PKGBASE}_ver${PKGVERSION}
PKGNAME=	clipper-6.4.2
CATEGORIES=	private
MASTER_SITES=	https://jaist.dl.sourceforge.net/project/polyclipping/
EXTRACT_SUFX=	.zip

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.angusj.com/delphi/clipper.php
COMMENT=	Clipping and offsetting lines and polygons
LICENSE=	boost-license

WRKSRC=		${WRKDIR}/cpp

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
